meta_product_name: "Juris Japan"
meta_title: "Juris Japan - The justice you need in Japan!"
meta_description: "Helping you with Japanese administrative procedures"
meta_image: "app/assets/images/logo-white.PNG"
